[package]
name = "rusty-framework"
version = "0.1.0"
edition = "2021"
default-run = "rusty-framework"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rusty-framework"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.12"
uuid = { version = "1.0", features = ["v4"] }
regex = "1.10"
tree-sitter = "0.20"
tree-sitter-c-sharp = "0.20"

[build-dependencies]
regex = "1.10"
tree-sitter = "0.20"
tree-sitter-c-sharp = "0.20"
